### ISSUE TITLE
its about dataset

### ISSUE THREAD

**Issue by ASSicat** [dahyun-kang/ifsl#13]
Hello, Thank you for your work. 
If I want to use my own dataset for training, what should I do?

**Comment by dahyun-kang** [comment]
Hello,

We currently do not support the custom dataset for training.

It can be mannually done by replicating dataset/pascal.py.
First, a set of images and a set of mask-labeled annotation in *.png (pixel-level class id) are required.
And place them in separate folders so that they can be read like:
 https://github.com/dahyun-kang/ifsl/blob/d0b0c0d1b01c036eaae1470585764d1321ec5336/fs-cs/data/pascal.py#L35-L36



Best,
Dahyun.
