### ISSUE TITLE
code for nshot > 1

### ISSUE THREAD

**Issue by LexieYang** [dahyun-kang/ifsl#3]
Hi @dahyun-kang,

Thanks for sharing your work. I was wondering if you will release code when args.shot > 1.

Best,
Minmin

**Comment by dahyun-kang** [comment]
Hi Minmin

Thank you for your interest! And yes I did, the `args.shot > 1` code is already implemented in this repo! 
Instead of training K-different K-shot learners, **I trained one 1-shot learner and evaluated it on arbitrary K shot episodes**, which not only reduces training effort but also is observed to generalize well. 
In practice, K-shot learners are evaluated with the python command with `--shot K`, and it is supposed to work with the `--eval` flag.

Have a great day! 😃 

Best,
Dahyun

**Comment by LexieYang** [comment]
Hi Dahyun,

Thanks for your clarificaition! 

Best,
Minmin
